### PR TITLE
remove DC-Planet as it seems down

### PR DESCRIPTION
**Pull request by Kcchouette**

### CODE REVIEW

**Comment by Kcchouette** [comment]
ping @pulsar-de @Sopor @blasti

**Comment by Kcchouette** [comment]
ping @pulsar-de @Sopor @blasti

**Comment by pulsar-de** [comment]
The forum is coming online again in the next few weeks.

**Comment by Kcchouette** [comment]
lol nice 3 years later

**Comment by Kcchouette** [comment]
ah ok I didn't know

**Pull request closed without merging**
